### ISSUE TITLE
Updating docker image to cover Log4j Solr vulnerability.

### ISSUE THREAD

**Issue by jt-moriarty** [nbgallery/nbgallery-solr#1]
Hello, I thought this would be the best place to mention that to address #https://github.com/advisories/GHSA-xxfh-x98p-j8fr you should consider updating the nbgallery-solr image currently on Docker Hub ASAP. The solr image you use as a base has already been fixed and updated, so a simple rebuild and update to Docker Hub should be sufficient. Thanks!

**Comment by mcrutch** [comment]
Sorry we missed this, but we did upgrade to 8.11.1 a while back (which solves all of the log4j vulnerabilities that Solr was potentially vulnerable to) but we are also in the process of trying to upgrade to 9.0 which even patches up to latest so scanning tools will be happy.
